<a href="https://colab.research.google.com/github/CustodioJustin/Linear-Algebra-58019/blob/main/Application.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Suppose, a market seller sold 20 apples and 10 orange in one day for total 350 pesos. The next day he sold 17 apples and 22 oranges for 500 pesos. If the price of the fruits remained unchanged on both the days, what was the price of one apple and one orange.

In [23]:
# 20x+10y = 350
# 17x+22y = 500

In [24]:
import numpy as np
from scipy.linalg import solve

A = np.array([[20,10],
              [17,22]])

B = np.array([[350],
              [500]])

print(A,'\n\n', B, '\n')

# eq01 = np.linalg.inv(A).dot(B)
        # Past Method

# eq01 = np.linalg.solve(A, B)
        # Numpy

eq01 = solve(A, B)

print(eq01)

[[20 10]
 [17 22]] 

 [[350]
 [500]] 

[[10.]
 [15.]]


In [29]:
# 4x+3y+2z = 25
# -2z+2y-3z = -10
# 3x-5y+2z = -4

# import numpy as np
# from scipy.linalg import solve
          # Using what's above

A = np.array([[4,3,2],
              [-2,2,3],
              [3,-5,2]])

B = np.array([[25],
              [-10],
              [-4]])

print(A,'\n\n', B, '\n')

eq02 = solve(A, B)

print(eq02)

[[ 4  3  2]
 [-2  2  3]
 [ 3 -5  2]] 

 [[ 25]
 [-10]
 [ -4]] 

[[ 5.]
 [ 3.]
 [-2.]]
