<a href="https://colab.research.google.com/github/CustodioJustin/Linear-Algebra-58019/blob/main/Coding_Activity_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

A = np.array([[4,10,8], [10,26,26], [8,26,61]])
B = np.array([[44],[128],[214]])
print(A)
print()
print(B)
print()
X = np.linalg.inv(A).dot(B)
print(X)
print()
print(np.dot(A,X))
print()
print("Proof")
print("4x+10y+8z =", (4*X[0])+(10*X[1])+(8*X[2]))
print("10x+26y+26z =", (10*X[0])+(26*X[1])+(26*X[2]))
print("8x+26y+61z =", (8*X[0])+(26*X[1])+(61*X[2]))

[[ 4 10  8]
 [10 26 26]
 [ 8 26 61]]

[[ 44]
 [128]
 [214]]

[[-8.]
 [ 6.]
 [ 2.]]

[[ 44.]
 [128.]
 [214.]]

Proof
4x+10y+8z = [44.]
10x+26y+26z = [128.]
8x+26y+61z = [214.]
