<a href="https://colab.research.google.com/github/CustodioJustin/Linear-Algebra-58019/blob/main/Eigenvalue_and_Eigenvector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Examples

In [5]:
# Example 1

import numpy as np
#from numpy.linalg import solve
from numpy.linalg import eig

A = np.array([[-12,3],
              [4,1]])

print(A, "\n")

inv_A = np.linalg.inv(A)
print(inv_A, "\n")

B = np.array([[0], [0]])
print(B, "\n")

X = np.dot(inv_A, B)
print(X, "\n")

# X = solve(A, B)
# print(X, "\n")

[[-12   3]
 [  4   1]] 

[[-0.04166667  0.125     ]
 [ 0.16666667  0.5       ]] 

[[0]
 [0]] 

[[0.]
 [0.]] 



In [13]:
# Example 2

A = np.array([[2,2,4],
              [1,3,5],
              [2,3,4]])
print(A, "\n")

s,t = np.linalg.eig(A)
print(s.round(), "\n\n", t.round(), "\n")

c = np.dot(A,t)
print(c, "\n")

[[2 2 4]
 [1 3 5]
 [2 3 4]] 

[ 9.  1. -1.] 

 [[-1. -1. -0.]
 [-1.  1. -1.]
 [-1. -0.  1.]] 

[[-4.65117886 -0.71834086  0.26674036]
 [-5.32417921  0.57681538  0.52235452]
 [-5.25556986 -0.09557072 -0.44358584]] 



In [17]:
f = np.array([[-1],
              [-1],
              [-1]])
print(f, "\n")

g = np.dot(A, f)
print(g, "\n")

[[-1]
 [-1]
 [-1]] 

[[-8]
 [-9]
 [-9]] 

