<a href="https://colab.research.google.com/github/CustodioJustin/Linear-Algebra-58019/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Problem 1. Student A, Student B, and Student C have a total of Php 89 cash in
# their banks. Student A has 6 less than Student C. Student B has 3 times what 
# Student C has. How much does each student have? (30 points)

import numpy as np
from scipy.linalg import solve

# -6A+3B+C = 89

A = np.array([[1,1,1],[1,0,4],[0,0,5]])
B = np.array([[89],[89],[95]])
amount = np.linalg.inv(A).dot(B)
print(amount)


[[13.]
 [57.]
 [19.]]


In [ ]:
# Problem 2. Solve each system: (30 points)

A1 = np.array([[3,-1,1], [9,-3,3], [-12,4,-4]])
B1 = np.array([[5], [15], [-20]])

print(A1, "\n")
print(B1, "\n")

#ans2 = solve(A1, B1)
#print(ans2, '\n')

print(' ERROR: LinAlgError: Singular Matrix')
print(' This problem gives an error mainly because ')
print(' It gives a determinant of 0 therefor ')
print(' Inverse of the matrix does not exist ')

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]] 

[[  5]
 [ 15]
 [-20]] 

 ERROR: LinAlgError: Singular Matrix
 This problem gives an error mainly because 
 It gives a determinant of 0 therefor 
 Inverse of the matrix does not exist 


In [ ]:
# Problem 3. Consider the matrix, (40 points)

A2 = np.array([[8,5,-6],
              [-12,-9,12],
              [-3,-3,5]])

print(A2, '\n')

z,x = np.linalg.eig(A2)
print("The Eigenvalues are: \n", z, "\n")

print("The Eigenvectors are: \n", x.round())

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]] 

The Eigenvalues are: 
 [-1.  3.  2.] 

The Eigenvectors are: 
 [[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
