<a href="https://colab.research.google.com/github/CustodioJustin/Linear-Algebra-58019/blob/main/Linear_Transformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

A = np.array([[4,3], [-5,9]])
print(A)
inv_A = np.linalg.inv(A)
print(inv_A)

[[ 4  3]
 [-5  9]]
[[ 0.17647059 -0.05882353]
 [ 0.09803922  0.07843137]]


In [ ]:
B = np.array([[20],[26]])
print(B)
X = np.linalg.inv(A).dot(B)
print(X)

[[20]
 [26]]
[[2.]
 [4.]]


In [ ]:
X = np.dot(inv_A,B)
print(X)

[[2.]
 [4.]]


In [34]:
A2 = np.array([[20,10], [17,22]])
B2 = np.array([[350],[500]])
print(A2)
print()
print(B2)
print()
X2 = np.linalg.inv(A2).dot(B2)
print(X2)
print()
print(np.dot(A2,X2))

[[20 10]
 [17 22]]

[[350]
 [500]]

[[10.]
 [15.]]

[[350.]
 [500.]]


In [33]:
A1 = np.array([[4,3,2], [-2,2,3], [3,-5,2]])
B1 = np.array([[25],[-10],[-4]])
print(A1)
print()
print(B1)
print()
X1 = np.linalg.inv(A1).dot(B1)
print(X1)
print()
print(np.dot(A1,X1))

[[ 4  3  2]
 [-2  2  3]
 [ 3 -5  2]]

[[ 25]
 [-10]
 [ -4]]

[[ 5.]
 [ 3.]
 [-2.]]

[[ 25.]
 [-10.]
 [ -4.]]
