<a href="https://colab.research.google.com/github/CustodioJustin/Linear-Algebra-58019/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
import numpy as np
A = np.array([[1,2],[4,7]])
B = np.linalg.inv(A)
print(B)

[[-7.  2.]
 [ 4. -1.]]


In [4]:
import numpy as np
A = np.array([[1,2],[4,7]])
invA = np.linalg.inv(A)
print(invA)

[[-7.  2.]
 [ 4. -1.]]


In [5]:
C = np.dot(A,invA)
print(C)

[[1. 0.]
 [0. 1.]]


In [ ]:
##Python program to Inverse 3x3 Matrix A = ()

In [11]:
A = np.array([[6,1,1],[4,-2,5],[2,8,7]])
print(A)
B = np.transpose(A)
print(B)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
[[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]


In [12]:
A = np.array([[6,1,1],[4,-2,5],[2,8,7]])
print(A)
B = np.linalg.inv(A)
print(B)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


## Program Code Product of A and B

In [14]:
productAB = np.dot(A, B)
print(productAB)

[[ 1.00000000e+00  0.00000000e+00  2.77555756e-17]
 [-1.38777878e-17  1.00000000e+00  1.38777878e-17]
 [-4.16333634e-17  1.38777878e-16  1.00000000e+00]]
