<a href="https://colab.research.google.com/github/CustodioJustin/Linear-Algebra-58019/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Question 1

In [33]:
# Question 1. Create a Python code that displays a square matrix whose length
# is 5 (10 points)

import numpy as np

q1 = np.full((5,5), 1)
print(q1)


[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Question 2

In [34]:
# Question 2. Create a Python code that displays a square matrix whose elements
# below the principal diagonal are zero (10 points)

q2 = np.array([[1,2,3,4,5],[0,6,7,8,9],[0,0,10,11,12],[0,0,0,13,14],[0,0,0,0,15]])
print(q2)

[[ 1  2  3  4  5]
 [ 0  6  7  8  9]
 [ 0  0 10 11 12]
 [ 0  0  0 13 14]
 [ 0  0  0  0 15]]


## Question 3

In [45]:
# Question 3. Create a Python code that displays a square matrix which is
# symmetrical (10 points)

q3_a = np.array([[1,2,3],[2,4,5],[3,5,8]])
q3_b = np.array([[1,2,3],[2,4,5],[3,2,1]])
print(q3_a)
print('or')
print(q3_b)

[[1 2 3]
 [2 4 5]
 [3 5 8]]
or
[[1 2 3]
 [2 4 5]
 [3 2 1]]


## Question 4

In [36]:
# Question 4. What is the inverse of matrix C? Show your solution by python 
# coding. (20 points)

q4_a = np.array([[1,2,3],[2,3,3],[3,4,-2]])
q4 = np.linalg.inv(q4_a)
print(q4_a)
print()
print(q4)

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]

[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


## Question 5

In [46]:
# Question 5. What is the determinant of the given matrix in Question 4? Show 
# your solution by python coding. (20 points)

print(q4_a)
print(round(np.linalg.det(q4_a)))

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
5


## Question 6

In [48]:
# Question 6. Find the roots of the linear equations by showing its python codes
# (30 points)
# 5X1 + 4X2 + X3 = 3.4
# 10X1 + 9X2 + 4X3 = 8.8
# 10X1 + 13X2 + 15X3 = 19.2

print('given:')
print('5X1 + 4X2 + X3 = 3.4')
print('10X1 + 9X2 + 4X3 = 8.8')
print('10X1 + 13X2 + 15X3 = 19.2')
print()
q6_A = np.array([[5,4,1],[10,9,4],[10,13,15]])
q6_B = np.array([[3.4],[8.8],[19.2]])
print(q6_A)
print(q6_B)
print()
q6 = np.linalg.inv(q6_A).dot(q6_B)
print(q6)
print()
print('proof')
print('X1 =',q6[0], 'X2 =',q6[1], 'X3 =',q6[2])
print()
print('5X1 + 4X2 + X3 =',(5*q6[0])+(4*q6[1])+(q6[2]))
print('10X1 + 9X2 + 4X3 =',(10*q6[0])+(9*q6[1])+(4*q6[2]))
print('10X1 + 13X2 + 15X3 =',(10*q6[0])+(13*q6[1])+(15*q6[2]))

given:
5X1 + 4X2 + X3 = 3.4
10X1 + 9X2 + 4X3 = 8.8
10X1 + 13X2 + 15X3 = 19.2

[[ 5  4  1]
 [10  9  4]
 [10 13 15]]
[[ 3.4]
 [ 8.8]
 [19.2]]

[[0.2]
 [0.4]
 [0.8]]

proof
X1 = [0.2] X2 = [0.4] X3 = [0.8]

5X1 + 4X2 + X3 = [3.4]
10X1 + 9X2 + 4X3 = [8.8]
10X1 + 13X2 + 15X3 = [19.2]
