<a href="https://colab.research.google.com/github/CustodioJustin/Linear-Algebra-58019/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Practical Lab Exam 1

In [38]:
import numpy as np

A = np.array([[1,2,3], [4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])
C = np.array([[1,2,3], [4,5,6], [7,8,9]])
D = np.array([[1,2],[3,4]])

print("Problem 1")
a = np.dot(A,B)
print(a)
print("")
b = np.add(D,D)
print(b)
print("")
c = 2*C
print(c)
print("")
print("Problem 2")
delta = np.array([5,3,-1])
print(delta)
print("")
print("Size: ",delta.size)
print("Shape: ",delta.shape)
print("Number of Dimension: ",delta.ndim)

Problem 1
[[22 28]
 [49 64]]

[[2 4]
 [6 8]]

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Problem 2
[ 5  3 -1]

Size:  3
Shape:  (3,)
Number of Dimension:  1
