<a href="https://colab.research.google.com/github/CustodioJustin/Linear-Algebra-58019/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##QUESTION 1

In [41]:
#Create a 4 x 4 matrix whose diagonal elements are all one (1's). 
#Name it as matrix "C". Show your solutions using Python codes and do not
#forget to label them on the Text Cell.
import numpy as np

C = np.full((4,4),1)
print(C)
q1 = np.diagonal(C)
print(q1)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[1 1 1 1]


##QUESTION 2

In [40]:
#In relation to Question 1, show a solution that doubles all the values of each
#element. Show your solutions using Python codes and do not forget to label
#them on the Text Cell.

q2_a = C*2
q2_b = q1*2
print("Double the value (Multiply by 2) of C from Question 1")
print(q2_a)
print(q2_b)

Double the value (Multiply by 2) of C from Question 1
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
[2 2 2 2]


##QUESTION 3

In [42]:
#Find the cross-product of matrices, A = [2,7,4] and B = [3,9,8]. 
#Show your solutions using Python codes and do not forget to label them on 
#the Text Cell.

A = np.array([2,7,4])
B = np.array([3,9,8])

print(A)
print(B)
q3 = np.cross(A,B)
print(q3)

[2 7 4]
[3 9 8]
[20 -4 -3]
