<a href="https://colab.research.google.com/github/CustodioJustin/Linear-Algebra-58019/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrices and Algebra operation

In [17]:
#Custodio Justin Chyle C.
import numpy as np

a = np.array([[-5,0],[4,1]])
b = np.array([[6, -3],[2,3]])
print(a)
print(b)

print("")
print("Operation Result")
print(a+b) #sum = A +B
print("")
print(b-a) #difference1 = B - A
print("")
print(a-b) #difference2 = A - B


[[-5  0]
 [ 4  1]]
[[ 6 -3]
 [ 2  3]]

Operation Result
[[ 1 -3]
 [ 6  4]]

[[11 -3]
 [-2  2]]

[[-11   3]
 [  2  -2]]
